/**
Susbstitute.java
@author Trushank
Date: Oct 15, 2013
 */
public class Susbstitute {

    public static void main(String[] args) {
	String CipherText="MFGAJKYSJUMKTAURYJCMJXFMLJLFAYSJAYDLKURSUIUMLJMJGJMXJARMUGMFCLUGCJAATYSFAFPPOTWFYTUCATCPFMFOOJOPMUXMFGGTCXFPPMUNTGFYTUCFOXUMTYSGAXFGJYSJUMKXJUGJYMKCDGHJMYSJUMKFCLUYSJMFMJFAURGFYSJGFYTWAFCLYSJUMJYTWFOWUGPDYJMAWTJCWJYSJWJCYMFOWUCWJPYTCMFGAJKYSJUMKTAYSFYURFMMUITCXMJAJFMWSUCYSJWUGPDYFYTUCFOFAPJWYAURMFGAJKYSJUMKYKPTWFOOKRFOOATCYUUCJURYIUFMJFAYSJWUGPDYFYTUCFOWUGPOJNTYKURPMUHOJGAMJOFYJLYUFMMUITCXFCLYSJWUGPDYFYTUCURWUCWMJYJMFGAJKCDGHJMAHUYSFMJFAFMJVJMKFWYTVJSUIJVJMDPYUCUITCYJMFWYTUCHJYIJJCYSJAJYIUMJAJFMWSAYMJFGASFAHJJCAPUMFLTWIJPMUPUAJYUHMTLXJYSJAJMJAJFMWSAYMJFGAFCLTCLUTCXAUUHYFTCCJITCATXSYAFCLCJIMJADOYATCHUYSFMJFA";
String SubstitutionKey="s-nu-ambweydrxlp-fhiovcgt-";
String PlainText=new String();
//Following key was found using cryptoanalysis
//abcdefghijklmnopqrstuvwxyz
//s-nu-ambweydrxlp-fhiovcgt-

for(int i=0;i<CipherText.length();i++){
   PlainText+= SubstitutionKey.charAt(CipherText.charAt(i)-65);
}
System.out.println(PlainText);
    }

}

